[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/itf-nexus-spark/*"
  to = "/itf-nexus-spark/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


